name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  # Customize the build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.head_ref}}
        fetch-depth: 0
        repository: ${{github.head_repo.full_name}}
    - name: Build
      # Build JasmineGraph docker image
      run: docker build -t jasminegraph .